[build]
  command = "npm install && npm run build"
  publish = "public"

[dev]
  command = "npm start"
  port = 3000
  publish = "public"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
